spring.application.name=ManjeetSinghPortfolio

# Server configuration
server.port=8080
server.servlet.context-path=/ManjeetSinghPortfolio

# Disable Thymeleaf cache during development so HTML changes refresh automatically
spring.thymeleaf.cache=false
